### ISSUE TITLE
Issue with the new year

### ISSUE THREAD

**Issue by soulesidibe** [gaelgthomas/mentor-statistics-openclassrooms#9]
Hello I am not able to see the stats for the current month (January 2020).
I've already done some sessions.  Check the screenshot below.
Thanks!
<img width="1190" alt="Screen Shot 2020-01-04 at 11 38 59" src="https://user-images.githubusercontent.com/936370/71765004-e35b7900-2ee6-11ea-8f26-67dd97bd9f18.png">

**Comment by gaelgthomas** [comment]
Hello,

This issue is fixed by [#7](https://github.com/gael-thomas/Mentor-Statistics-OpenClassRooms/pull/7).

If you use Firefox, please download [the last release 1.1.3](https://github.com/gael-thomas/Mentor-Statistics-OpenClassRooms/releases).
If you use Google Chrome, please wait or re-download [the extension on store](https://chrome.google.com/webstore/detail/mentor-statistics-opencla/ojihaopldjoohbbpidenkbnahhapfdjd).

Thank you!
